### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by jdesive** [Sw4pSpace/Cubed#1]
In order to ensure easy deployment of Cubed we would like to provide basic tools/files to deploy Cubed to a production environment. It would also be nice to support dev/staging environments as well.

We have a Jenkins server at http://jenkins.sw4pspace.net we need to supply a nightly build of cubed for testing and demonstration purposes. 

---

Tasks to complete:

Project:
- [ ] Provide Docker images for `db`, `server`, and `webservices` modules
- [ ] Provide a docker-compose file to deploy to docker 
- [ ] Provide a rancher-compose file to deploy to rancher 1.0
- [ ] Provide Kubernetes files to deploy to a kubernetes cluster
- [x] ~~#3 Provide scripts to deploy to a bare bones server (all-in-one)~~

Infrastructure: 
- [ ] Create a nightly build job in jenkins
